version: 2.3.{build}
image: Visual Studio 2017 Preview
clone_folder: C:\Projects\Victoria
skip_commits:
  message: /Update/
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet build
artifacts:
- path: '**\*.nupkg'
  name: Victoria
deploy:
- provider: NuGet
  api_key:
    secure: 2ERjvGaKjBby9aE8IHGo0uBHqXuosD3em2isgwubNPD9Zwt1q+y1WOopXW2dmH6j
  artifact: Victoria
